// This file is autogenerated by the hyperdispatch compiler
/* eslint-disable camelcase */

import { c, b4a, assert, DispatchError, ERRORS } from 'hyperdispatch/runtime'
import { version, getEncoding, setVersion } from './messages.js'

const defaultVersion = version

class Router {
  constructor () {
    this._handler0 = null
    this._handler1 = null
    this._handler2 = null
    this._handler3 = null
    this._handler4 = null
    this._handler5 = null
    this._handler6 = null
    this._handler7 = null

    this._missing = 8
  }

  add (name, handler) {
    switch (name) {
      case '@wdk-addressbook/put-contact':
        this._handler0 = handler
        break
      case '@wdk-addressbook/del-contact':
        this._handler1 = handler
        break
      case '@wdk-addressbook/put-address':
        this._handler2 = handler
        break
      case '@wdk-addressbook/del-address':
        this._handler3 = handler
        break
      case '@wdk-addressbook/add-writer':
        this._handler4 = handler
        break
      case '@wdk-addressbook/remove-writer':
        this._handler5 = handler
        break
      case '@wdk-addressbook/add-mirror':
        this._handler6 = handler
        break
      case '@wdk-addressbook/del-mirror':
        this._handler7 = handler
        break
      default:
        throw DispatchError.NONEXISTENT_ROUTE(name)
    }
    this._missing--
  }

  _checkAll () {
    assert(this._handler0 !== null, 'Missing handler for "@wdk-addressbook/put-contact"')
    assert(this._handler1 !== null, 'Missing handler for "@wdk-addressbook/del-contact"')
    assert(this._handler2 !== null, 'Missing handler for "@wdk-addressbook/put-address"')
    assert(this._handler3 !== null, 'Missing handler for "@wdk-addressbook/del-address"')
    assert(this._handler4 !== null, 'Missing handler for "@wdk-addressbook/add-writer"')
    assert(this._handler5 !== null, 'Missing handler for "@wdk-addressbook/remove-writer"')
    assert(this._handler6 !== null, 'Missing handler for "@wdk-addressbook/add-mirror"')
    assert(this._handler7 !== null, 'Missing handler for "@wdk-addressbook/del-mirror"')
  }

  async dispatch (message, context) {
    if (this._missing > 0) {
      this._checkAll()
    }

    setVersion(defaultVersion)

    const op = b4a.isBuffer(message) ? decode(message) : message

    switch (op.id) {
      case 0:
        return this._handler0(op.value, context)
      case 1:
        return this._handler1(op.value, context)
      case 2:
        return this._handler2(op.value, context)
      case 3:
        return this._handler3(op.value, context)
      case 4:
        return this._handler4(op.value, context)
      case 5:
        return this._handler5(op.value, context)
      case 6:
        return this._handler6(op.value, context)
      case 7:
        return this._handler7(op.value, context)
      default:
        throw DispatchError.HANDLER_NOT_FOUND_BY_ID(op.id)
    }
  }
}

function encode (name, message, { version = defaultVersion } = {}) {
  const state = { buffer: null, start: 0, end: 0 }

  const route = getRouteByName(name)
  setVersion(version)

  c.uint.preencode(state, route.id)
  route.enc.preencode(state, message)

  state.buffer = b4a.allocUnsafe(state.end)
  c.uint.encode(state, route.id)
  route.enc.encode(state, message)

  return state.buffer
}

function decode (buffer, { version = defaultVersion } = {}) {
  const state = { buffer, start: 0, end: buffer.length }

  const id = c.uint.decode(state)
  const route = getRouteById(id)
  setVersion(version)

  const value = route.enc.decode(state)
  return { id, name: route.name, value }
}

const route0 = {
  name: '@wdk-addressbook/put-contact',
  id: 0,
  enc: getEncoding('@wdk-addressbook/contact')
}

const route1 = {
  name: '@wdk-addressbook/del-contact',
  id: 1,
  enc: getEncoding('@wdk-addressbook/del-contact')
}

const route2 = {
  name: '@wdk-addressbook/put-address',
  id: 2,
  enc: getEncoding('@wdk-addressbook/address')
}

const route3 = {
  name: '@wdk-addressbook/del-address',
  id: 3,
  enc: getEncoding('@wdk-addressbook/del-address')
}

const route4 = {
  name: '@wdk-addressbook/add-writer',
  id: 4,
  enc: getEncoding('@wdk-addressbook/writer')
}

const route5 = {
  name: '@wdk-addressbook/remove-writer',
  id: 5,
  enc: getEncoding('@wdk-addressbook/writer')
}

const route6 = {
  name: '@wdk-addressbook/add-mirror',
  id: 6,
  enc: getEncoding('@wdk-addressbook/mirror')
}

const route7 = {
  name: '@wdk-addressbook/del-mirror',
  id: 7,
  enc: getEncoding('@wdk-addressbook/del-mirror')
}

function getRouteByName (name) {
  switch (name) {
    case '@wdk-addressbook/put-contact':
      return route0
    case '@wdk-addressbook/del-contact':
      return route1
    case '@wdk-addressbook/put-address':
      return route2
    case '@wdk-addressbook/del-address':
      return route3
    case '@wdk-addressbook/add-writer':
      return route4
    case '@wdk-addressbook/remove-writer':
      return route5
    case '@wdk-addressbook/add-mirror':
      return route6
    case '@wdk-addressbook/del-mirror':
      return route7
    default:
      throw DispatchError.ROUTE_NOT_FOUND_BY_NAME(name)
  }
}

function getRouteById (id) {
  switch (id) {
    case 0:
      return route0
    case 1:
      return route1
    case 2:
      return route2
    case 3:
      return route3
    case 4:
      return route4
    case 5:
      return route5
    case 6:
      return route6
    case 7:
      return route7
    default:
      throw DispatchError.HANDLER_NOT_FOUND_BY_ID(id)
  }
}

export {
  version,
  encode,
  decode,
  Router,
  DispatchError,
  ERRORS
}
