// This file is autogenerated by the hyperschema compiler
// Schema Version: 1
/* eslint-disable camelcase */
/* eslint-disable quotes */
/* eslint-disable space-before-function-paren */

import { c } from 'hyperschema/runtime'

const VERSION = 1

// eslint-disable-next-line no-unused-vars
let version = VERSION

// @wdk-addressbook/contact
const encoding0 = {
  preencode(state, m) {
    c.string.preencode(state, m.id)
    c.string.preencode(state, m.name)
    state.end++ // max flag is 1 so always one byte

    if (m.username) c.string.preencode(state, m.username)
    c.int.preencode(state, m.createdAt)
    c.int.preencode(state, m.updatedAt)
  },
  encode(state, m) {
    const flags = m.username ? 1 : 0

    c.string.encode(state, m.id)
    c.string.encode(state, m.name)
    c.uint.encode(state, flags)

    if (m.username) c.string.encode(state, m.username)
    c.int.encode(state, m.createdAt)
    c.int.encode(state, m.updatedAt)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: r0,
      name: r1,
      username: (flags & 1) !== 0 ? c.string.decode(state) : null,
      createdAt: c.int.decode(state),
      updatedAt: c.int.decode(state)
    }
  }
}

// @wdk-addressbook/address
const encoding1 = {
  preencode(state, m) {
    c.string.preencode(state, m.id)
    c.string.preencode(state, m.contactId)
    c.string.preencode(state, m.address)
    c.string.preencode(state, m.type)
    c.string.preencode(state, m.network)
    state.end++ // max flag is 1 so always one byte

    if (m.label) c.string.preencode(state, m.label)
    c.int.preencode(state, m.createdAt)
    c.int.preencode(state, m.updatedAt)
  },
  encode(state, m) {
    const flags = m.label ? 1 : 0

    c.string.encode(state, m.id)
    c.string.encode(state, m.contactId)
    c.string.encode(state, m.address)
    c.string.encode(state, m.type)
    c.string.encode(state, m.network)
    c.uint.encode(state, flags)

    if (m.label) c.string.encode(state, m.label)
    c.int.encode(state, m.createdAt)
    c.int.encode(state, m.updatedAt)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.string.decode(state)
    const r3 = c.string.decode(state)
    const r4 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: r0,
      contactId: r1,
      address: r2,
      type: r3,
      network: r4,
      label: (flags & 1) !== 0 ? c.string.decode(state) : null,
      createdAt: c.int.decode(state),
      updatedAt: c.int.decode(state)
    }
  }
}

// @wdk-addressbook/writer
const encoding2 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.key)
    state.end++ // max flag is 1 so always one byte

    if (m.name) c.string.preencode(state, m.name)
  },
  encode(state, m) {
    const flags = m.name ? 1 : 0

    c.buffer.encode(state, m.key)
    c.uint.encode(state, flags)

    if (m.name) c.string.encode(state, m.name)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const flags = c.uint.decode(state)

    return {
      key: r0,
      name: (flags & 1) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @wdk-addressbook/del-contact
const encoding3 = {
  preencode(state, m) {
    c.string.preencode(state, m.id)
  },
  encode(state, m) {
    c.string.encode(state, m.id)
  },
  decode(state) {
    const r0 = c.string.decode(state)

    return {
      id: r0
    }
  }
}

// @wdk-addressbook/del-address
const encoding4 = encoding3

// @wdk-addressbook/mirror
const encoding5 = {
  preencode(state, m) {
    c.fixed32.preencode(state, m.key)
  },
  encode(state, m) {
    c.fixed32.encode(state, m.key)
  },
  decode(state) {
    const r0 = c.fixed32.decode(state)

    return {
      key: r0
    }
  }
}

// @wdk-addressbook/del-mirror
const encoding6 = encoding5

// @wdk-addressbook/contact/hyperdb#0
const encoding7 = {
  preencode(state, m) {
    c.string.preencode(state, m.name)
    state.end++ // max flag is 1 so always one byte

    if (m.username) c.string.preencode(state, m.username)
    c.int.preencode(state, m.createdAt)
    c.int.preencode(state, m.updatedAt)
  },
  encode(state, m) {
    const flags = m.username ? 1 : 0

    c.string.encode(state, m.name)
    c.uint.encode(state, flags)

    if (m.username) c.string.encode(state, m.username)
    c.int.encode(state, m.createdAt)
    c.int.encode(state, m.updatedAt)
  },
  decode(state) {
    const r1 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: null,
      name: r1,
      username: (flags & 1) !== 0 ? c.string.decode(state) : null,
      createdAt: c.int.decode(state),
      updatedAt: c.int.decode(state)
    }
  }
}

// @wdk-addressbook/address/hyperdb#1
const encoding8 = {
  preencode(state, m) {
    c.string.preencode(state, m.contactId)
    c.string.preencode(state, m.address)
    c.string.preencode(state, m.type)
    c.string.preencode(state, m.network)
    state.end++ // max flag is 1 so always one byte

    if (m.label) c.string.preencode(state, m.label)
    c.int.preencode(state, m.createdAt)
    c.int.preencode(state, m.updatedAt)
  },
  encode(state, m) {
    const flags = m.label ? 1 : 0

    c.string.encode(state, m.contactId)
    c.string.encode(state, m.address)
    c.string.encode(state, m.type)
    c.string.encode(state, m.network)
    c.uint.encode(state, flags)

    if (m.label) c.string.encode(state, m.label)
    c.int.encode(state, m.createdAt)
    c.int.encode(state, m.updatedAt)
  },
  decode(state) {
    const r1 = c.string.decode(state)
    const r2 = c.string.decode(state)
    const r3 = c.string.decode(state)
    const r4 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      id: null,
      contactId: r1,
      address: r2,
      type: r3,
      network: r4,
      label: (flags & 1) !== 0 ? c.string.decode(state) : null,
      createdAt: c.int.decode(state),
      updatedAt: c.int.decode(state)
    }
  }
}

// @wdk-addressbook/writer/hyperdb#3
const encoding9 = {
  preencode(state, m) {
    state.end++ // max flag is 1 so always one byte

    if (m.name) c.string.preencode(state, m.name)
  },
  encode(state, m) {
    const flags = m.name ? 1 : 0

    c.uint.encode(state, flags)

    if (m.name) c.string.encode(state, m.name)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      key: null,
      name: (flags & 1) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @wdk-addressbook/mirror/hyperdb#4
const encoding10 = {
  preencode(state, m) {

  },
  encode(state, m) {

  },
  decode(state) {
    return {
      key: null
    }
  }
}

function setVersion(v) {
  version = v
}

function encode(name, value, v = VERSION) {
  version = v
  return c.encode(getEncoding(name), value)
}

function decode(name, buffer, v = VERSION) {
  version = v
  return c.decode(getEncoding(name), buffer)
}

function getEnum(name) {
  switch (name) {
    default:
      throw new Error('Enum not found ' + name)
  }
}

function getEncoding(name) {
  switch (name) {
    case '@wdk-addressbook/contact':
      return encoding0
    case '@wdk-addressbook/address':
      return encoding1
    case '@wdk-addressbook/writer':
      return encoding2
    case '@wdk-addressbook/del-contact':
      return encoding3
    case '@wdk-addressbook/del-address':
      return encoding4
    case '@wdk-addressbook/mirror':
      return encoding5
    case '@wdk-addressbook/del-mirror':
      return encoding6
    case '@wdk-addressbook/contact/hyperdb#0':
      return encoding7
    case '@wdk-addressbook/address/hyperdb#1':
      return encoding8
    case '@wdk-addressbook/writer/hyperdb#3':
      return encoding9
    case '@wdk-addressbook/mirror/hyperdb#4':
      return encoding10
    default:
      throw new Error('Encoder not found ' + name)
  }
}

function getStruct(name, v = VERSION) {
  const enc = getEncoding(name)
  return {
    preencode(state, m) {
      version = v
      enc.preencode(state, m)
    },
    encode(state, m) {
      version = v
      enc.encode(state, m)
    },
    decode(state) {
      version = v
      return enc.decode(state)
    }
  }
}

const resolveStruct = getStruct // compat

export { resolveStruct, getStruct, getEnum, getEncoding, encode, decode, setVersion, version }
