name: build

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    timeout-minutes: 5
    steps:
      - uses: tetherto/oss-actions/node-base@v1
      - run: npm run lint
  test:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
    runs-on: ${{ matrix.os }}
    name: Test / ${{ matrix.platform }}
    timeout-minutes: 10
    steps:
      - uses: tetherto/oss-actions/node-base@v1
      - run: npm run brittle
      - run: npm run test:p2p
      - run: npm run test:bare
